kind: pipeline
type: docker
name: linux-arm

platform:
  arch: arm
  os: linux

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: gelse/mh_z19-dockerized
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest
    dockerfile: ./Dockerfile
    registry: registry.gelse.dev
    