kind: pipeline
type: docker
name: linux-arm64

platform:
  arch: arm64
  os: linux

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: gelse/mh_z19-dockerized
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: "true"
    auto_tag_suffix: linux-arm64
    dockerfile: Dockerfile.arm
    registry: registry.gelse.dev
  when:
    event:
      - push
      - tag
    
kind: pipeline
type: docker
name: linux-arm

platform:
  arch: arm
  os: linux

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: gelse/mh_z19-dockerized
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: "true"
    auto_tag_suffix: linux-arm
    dockerfile: Dockerfile.arm
    registry: registry.gelse.dev
  when:
    event:
      - push
      - tag